swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /users:
    get:
      description: Returns a list of users
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/MessageResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  MessageResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  User:
    properties:
      username:
        type: string
  DataFrame:
    properties:
      data:
        type: array
        items:
          type: array
          items:
            type: number
      columns:
        type: array
        items:
          type: string
